on: [push]

name: test

jobs:
  centos:
    container: centos:8
    runs-on: [self-hosted, Linux, X64]
    env:
      GHA_EXTERNAL_DISK: "auxdisk"
      GHA_PREEMPTIBLE: "false"
      KEYS: "${{ secrets.KEYS }}"
      
    steps:
    - run: df -h .
    - run: df -h /mnt/aux
    - run: ls -alh /mnt/aux
    - run: _secret_custom_get_tools_v2
    - run: ls -lah .
