on: [push]

name: test

jobs:
  centos:
    container: centos:8
    runs-on: [self-hosted, Linux, X64, gcp-disk-test]
    env:
      GHA_EXTERNAL_DISK: "auxdisk"
      GHA_PREEMPTIBLE: "false"
      KEYS: "${{ secrets.KEYS }}"
      
    steps:
    - run: df -h .
    - run: df -h /mnt/aux
    - run: ls -alh /mnt/aux
    - run: |
        cat /etc/resolv.conf
        echo "nameserver 1.1.1.1" > /etc/resolv.conf
        sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-*
        sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-*
        dnf install -y wget
        wget --version 
    - run: _secret_custom_get_tools_v2
    - run: ls -lah .
